### ISSUE TITLE
optimize bg-size-cover, bg-size-contain, bg-size-... to bg-contain

### ISSUE THREAD

**Issue by CodenNerd** [CodenNerd/GenericCss#10]

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by CodenNerd** [comment]
Hi @Pulkitxm Thanks for trying to contribute but this issue has been addressed. Kindly help with a different issue. Also feel free to try out the compiler and raise other issues you observe. The compiler is fairly new so there'll be many to resolve. Thanks once again.
